### ISSUE TITLE
`npm test` fails

### ISSUE THREAD

**Issue by sbstnmsch** [chris5marsh/grunt-makedocs#2]
Hey Chris,
I like your module! Unfortunately I am not able to get it to work. I submitted a PR https://github.com/chris5marsh/grunt-makedocs/pull/1 for adding basic travis-ci integration to make it more transparently in the future.

Cheers,
Sebastian

**Comment by sbstnmsch** [comment]
Here is the stacktrace:

```
$ grunt makedocs --stack
Running "makedocs:default" (makedocs) task
Warning: Unable to read "undefined" file (Error code: ENOENT). Use --force to continue.
Error: ENOENT, no such file or directory 'undefined'
    at Error (native)
    at Object.fs.openSync (fs.js:500:18)
    at Object.fs.readFileSync (fs.js:352:15)
    at Object.file.read (/.../node_modules/grunt/lib/grunt/file.js:233:19)
    at /.../node_modules/grunt-makedocs/tasks/makedocs.js:168:42
    at diveSync (/.../node_modules/grunt-makedocs/node_modules/diveSync/diveSync.js:62:5)
    at MAKEDOCS.setupComponents (/.../node_modules/grunt-makedocs/tasks/makedocs.js:166:9)
    at MAKEDOCS.run (/.../node_modules/grunt-makedocs/tasks/makedocs.js:113:14)
    at Object.<anonymous> (/.../node_modules/grunt-makedocs/tasks/makedocs.js:244:14)
    at Object.<anonymous> (/.../node_modules/grunt/lib/grunt/task.js:264:15)

Aborted due to warnings.

```

**Comment by chris5marsh** [comment]
Hi Sebastian,

Thanks for getting involved! I wrote the makedocs module for a fairly specific use case, and published it in case anyone else might have a need for it, so I'm not surprised if there are a few things wrong.

I haven't looked into Travis much, but I'll do a bit of investigating when I have the time and if I want to include it I'll merge your PR.

Thanks!
